# Generated by Django 5.2.dev20241015152339 on 2024-11-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_usermeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='langue',
            field=models.CharField(choices=[('', 'Choisissez votre langue'), ('fr', 'Français'), ('en', 'English'), ('nl', 'Nederlands')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL),
        ),
    ]
