# Generated by Django 5.1.2 on 2025-01-13 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_representation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artiste_types', to='catalogue.artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artiste_types', to='catalogue.type')),
            ],
            options={
                'db_table': 'artiste_type',
            },
        ),
    ]
