# Generated by Django 5.2 on 2025-04-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_representation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('slug', 'created_in'), name='unique_slug_created_in'),
        ),
    ]
