# Generated by Django 5.2 on 2025-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_artist_types_alter_artist_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='types',
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('firstname', 'lastname'), name='unique_firstname_lastname'),
        ),
    ]
