# Generated by Django 5.2 on 2025-04-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_remove_artist_types_artist_unique_firstname_lastname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': False},
        ),
    ]
