# Generated by Django 5.2 on 2025-04-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_usermeta_langue_alter_usermeta_user'),
        ('catalogue', '0016_artisttypeshow_show_artist_types'),
    ]

    operations = [
    ]
