# Generated by Django 5.2 on 2025-04-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_showprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='prices',
            field=models.ManyToManyField(related_name='shows', through='catalogue.ShowPrice', to='catalogue.price'),
        ),
        migrations.CreateModel(
            name='RepresentationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogue.price')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.representation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.reservation')),
            ],
            options={
                'db_table': 'representation_reservations',
                'unique_together': {('representation', 'reservation', 'price')},
            },
        ),
        migrations.AddField(
            model_name='representation',
            name='reservations',
            field=models.ManyToManyField(related_name='representations', through='catalogue.RepresentationReservation', to='catalogue.reservation'),
        ),
    ]
