# Generated by Django 5.2 on 2025-04-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_show_prices_representationreservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show')),
            ],
            options={
                'db_table': 'artist_show',
                'unique_together': {('artist', 'show')},
            },
        ),
    ]
