# Generated by Django 5.2 on 2025-04-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='show',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='representation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.representation'),
            preserve_default=False,
        ),
    ]
