# Generated by Django 5.2 on 2025-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_remove_cartitem_show_cartitem_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='active_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='langue',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
