# Generated by Django 5.2 on 2025-04-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_usermeta_active_token_alter_usermeta_langue'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='langue',
            field=models.CharField(max_length=2),
        ),
    ]
