# Generated by Django 5.2 on 2025-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_cartitem_price_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troupe',
            fields=[
                ('id', models.AutoField(help_text='Id de la troupe', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom de la troupe', max_length=60, unique=True)),
                ('logo_url', models.CharField(blank=True, help_text='URL du logo de la troupe', max_length=250, null=True)),
            ],
            options={
                'db_table': 'troupes',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_troupe_name')],
            },
        ),
    ]
