# Generated by Django 5.2 on 2025-05-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_troupe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
