# Generated by Django 5.2 on 2025-05-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_alter_artist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='shows',
            field=models.ManyToManyField(related_name='artists', through='catalogue.ArtistShow', to='catalogue.show'),
        ),
        migrations.AddField(
            model_name='artist',
            name='troupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='catalogue.troupe'),
        ),
    ]
